package com.example.eplan.presentation.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF3248ea)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdee0ff)
val md_theme_light_onPrimaryContainer = Color(0xFF000767)
val md_theme_light_secondary = Color(0xFF5b5d72)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe0e0f9)
val md_theme_light_onSecondaryContainer = Color(0xFF181a2c)
val md_theme_light_tertiary = Color(0xFF77536c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd7f1)
val md_theme_light_onTertiaryContainer = Color(0xFF2d1227)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbff)
val md_theme_light_onBackground = Color(0xFF1b1b1f)
val md_theme_light_surface = Color(0xFFfffbff)
val md_theme_light_onSurface = Color(0xFF1b1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe3e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF46464e)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFf3f0f5)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFbbc3ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFbbc3ff)
val md_theme_dark_onPrimary = Color(0xFF0012a1)
val md_theme_dark_primaryContainer = Color(0xFF0928d3)
val md_theme_dark_onPrimaryContainer = Color(0xFFdee0ff)
val md_theme_dark_secondary = Color(0xFFc4c5dd)
val md_theme_dark_onSecondary = Color(0xFF2d2f42)
val md_theme_dark_secondaryContainer = Color(0xFF434559)
val md_theme_dark_onSecondaryContainer = Color(0xFFe0e0f9)
val md_theme_dark_tertiary = Color(0xFFe6bad6)
val md_theme_dark_onTertiary = Color(0xFF45263d)
val md_theme_dark_tertiaryContainer = Color(0xFF5e3c54)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd7f1)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1f)
val md_theme_dark_onBackground = Color(0xFFe4e1e6)
val md_theme_dark_surface = Color(0xFF1b1b1f)
val md_theme_dark_onSurface = Color(0xFFe4e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF46464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc7c5d0)
val md_theme_dark_outline = Color(0xFF91909a)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe4e1e6)
val md_theme_dark_inversePrimary = Color(0xFF3248ea)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF0023d1)
val error = Color(0xFFba1b1b)